backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "/public/images"
public_folder: /images
site_url: https://codeheree.netlify.app

collections:
  - name: "home_page"
    label: "Home page"
    create: false
    editor:
      preview: false
    files:
      - name: "meta_data"
        label: "Page meta data"
        file: "/_content/metaData.json"
        description: "Edit home page's meta data."
        fields:
          - name: "title"
            label: "Page title"
            widget: "string"
          - name: "description"
            label: "Page description"
            widget: "string"
          - name: "discord_link"
            label: "Discord link"
            widget: "string"
      - name: "intro"
        label: "Intro section"
        file: "/_content/intro.json"
        description: "Edit home page's intro section."
        fields:
          - name: "heading"
            label: "Heading"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it highlighted. Put text between triple asterisks (***text***) to make it highlighted & italic."
          - name: "paragraph"
            label: "Paragraph"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
          - name: "call_to_action"
            label: "Call to action"
            widget: "object"
            fields:
              - name: "text"
                label: "Text"
                widget: "string"
                hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
              - name: "link"
                label: "Link"
                widget: "string"
      - name: "about"
        label: "About section"
        file: "/_content/about.json"
        description: "Edit home page's about section."
        preview_path: "#about"
        fields:
          - name: "illustration"
            label: "Illustration"
            widget: "object"
            fields:
              - name: "src"
                label: "Image"
                widget: "image"
              - name: "alt"
                label: "Alt text"
                widget: "string"
              - name: "title"
                label: "Title"
                widget: "string"
          - name: "heading"
            label: "Heading"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it highlighted. Put text between triple asterisks (***text***) to make it highlighted & italic."
          - name: "paragraph"
            label: "Paragraph"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
          - name: "call_to_action"
            label: "Call to action"
            widget: "object"
            fields:
              - name: "text"
                label: "Text"
                widget: "string"
                hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
              - name: "link"
                label: "Link"
                widget: "string"
      - name: "projects"
        label: "Projects section"
        file: "/_content/projects.json"
        description: "Edit home page's projects section."
        preview_path: "#projects"
        fields:
          - name: "illustration"
            label: "Illustration"
            widget: "object"
            fields:
              - name: "src"
                label: "Image"
                widget: "image"
              - name: "alt"
                label: "Alt text"
                widget: "string"
              - name: "title"
                label: "Title"
                widget: "string"
          - name: "heading"
            label: "Heading"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it highlighted. Put text between triple asterisks (***text***) to make it highlighted & italic."
          - name: "paragraph"
            label: "Paragraph"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
          - name: "call_to_action"
            label: "Call to action"
            widget: "object"
            fields:
              - name: "text"
                label: "Text"
                widget: "string"
                hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
              - name: "link"
                label: "Link"
                widget: "string"
      - name: "discover"
        label: "Discover section"
        file: "/_content/discover.json"
        description: "Edit home page's discover section."
        preview_path: "#discover-people"
        fields:
          - name: "illustration"
            label: "Illustration"
            widget: "object"
            fields:
              - name: "src"
                label: "Image"
                widget: "image"
              - name: "alt"
                label: "Alt text"
                widget: "string"
              - name: "title"
                label: "Title"
                widget: "string"
          - name: "heading"
            label: "Heading"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it highlighted. Put text between triple asterisks (***text***) to make it highlighted & italic."
          - name: "paragraph"
            label: "Paragraph"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
          - name: "call_to_action"
            label: "Call to action"
            widget: "object"
            fields:
              - name: "text"
                label: "Text"
                widget: "string"
                hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
              - name: "link"
                label: "Link"
                widget: "string"
      - name: "help"
        label: "Help section"
        file: "/_content/help.json"
        description: "Edit home page's help section."
        preview_path: "#get-help"
        fields:
          - name: "illustration"
            label: "Illustration"
            widget: "object"
            fields:
              - name: "src"
                label: "Image"
                widget: "image"
              - name: "alt"
                label: "Alt text"
                widget: "string"
              - name: "title"
                label: "Title"
                widget: "string"
          - name: "heading"
            label: "Heading"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it highlighted. Put text between triple asterisks (***text***) to make it highlighted & italic."
          - name: "paragraph"
            label: "Paragraph"
            widget: "text"
            hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
          - name: "call_to_action"
            label: "Call to action"
            widget: "object"
            fields:
              - name: "text"
                label: "Text"
                widget: "string"
                hint: "Put text between asterisks (*text*) to make it italic. Put text between double asterisks (**text**) to make it bold. Put text between triple asterisks (***text***) to make it bold & italic."
              - name: "link"
                label: "Link"
                widget: "string"